apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vaktor
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://vaktor.dev.nav.no
    env:
        - name: NPM_CONFIG_CACHE
          value: /tmp
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true
            tenant: nav.no
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
        sidecar:
            enabled: true
            # everything below is optional, defaults shown
            autoLogin: true
            errorPath: ""
