apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vaktor
    namespace: navdig
    labels:
        team: navdig
spec:
    accessPolicy:
        inbound:
            rules:
                - application: vaktor-plan
        outbound:
            rules:
                - application: vaktor-plan
    image: {{ image }}
    port: 3000
    ingresses:
        - https://vaktor.dev.nav.no
    env:
        - name: NPM_CONFIG_CACHE
          value: /tmp
        - name: BACKEND_URL
          value: http://vaktor-plan-api
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true
            tenant: nav.no
            allowAllUsers: true
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            singlePageApplication: false
        sidecar:
            enabled: true
            # everything below is optional, defaults shown
            autoLogin: true
            errorPath: ""
