apiVersion: nais.io/v2
kind: Application
metadata:
    name: vaktor
    namespace: vaktor   
    labels:
        team: vaktor
spec:
    accessPolicy:
        inbound:
            rules:
                - application: vaktor-plan
                - application: ida # Allow IDA users to test this proxy in dev.
                  namespace: traktor
                  cluster: prod-fss #IDA users come from the production environment.
        outbound:
            rules:
                - application: vaktor-plan
                - application: fullmaktsregister-external-proxy
                  namespace: team-nof
                  cluster: dev-gcp
    image: {{ image }}
    port: 3000
    ingresses:
        - https://vaktor.intern.dev.nav.no
    env:
    {{#each env}}
        - name: {{this.name}}
          value: "{{this.value}}"
    {{/each}}
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true
            tenant: trygdeetaten.no
            allowAllUsers: true
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            singlePageApplication: false
        sidecar:
            enabled: true
            # everything below is optional, defaults shown
            autoLogin: true