apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vaktor
    namespace: navdig
    labels:
        team: navdig
spec:
    accessPolicy:
        inbound:
            rules:
                - application: vaktor-plan
        outbound:
            rules:
                - application: vaktor-plan
    image: {{ image }}
    port: 3000
    ingresses:
        - https://vaktor.ansatt.nav.no
    env:
    {{#each env}}
        - name: {{this.name}}
          value: "{{this.value}}"
    {{/each}}
    replicas:
        min: 2
        max: 2
    resources:
        limits:
            cpu: "1000m"
            memory: "1024Mi"
        requests:
            cpu: "1000m"
            memory: "1024Mi"
    azure:
        application:
            enabled: true
            tenant: nav.no
            allowAllUsers: true
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            singlePageApplication: false
        sidecar:
            enabled: true
            # everything below is optional, defaults shown
            autoLogin: true
